### ISSUE TITLE
탐험형 던전 구현

### ISSUE THREAD

**Issue by Eu4ng** [E4-Unity/unity-dont-stop#1]
# 요구 사항
- 씬 구성
- 보스 패턴 구현

**Comment by GongByeongYeon** [comment]
# 씬 구성
## 엘리트 스테이지
- [x] 미로식 구성
- [ ] 스폰포인트 배치 후 아이템 및 엘리트 몬스터 생성
- [ ] 엘리트 몬스터 처치 후 포탈 활성화
- [ ] 포탈에 들어가면 보스 스테이지 진입
## 보스 스테이지
- [ ] 메이즈, 포탈 비활성화
- [ ] 배경, 보스, HUD 활성화

# 보스 패턴 구현
## 슬라임 보스
- 계속 추격하며 근접해서 데미지를 누적시키는 보스 패턴 방식
- [x] 이동 : 점프, 공격 애니메이션 구현
- [x] 점프 전 플레이어 마지막 위치를 향해 일직선으로 점프
- [x] 플레이어와 근접하면 공격 애니메이션 재생
